name: 'Discord Notifications'
description: 'Outputs a message to Discord.'
author: Tharit
branding:
  icon: message-square
  color: gray-dark
inputs:
  args:
    description: 'The message to display in the Discord message.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
