name: Notification on push

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEB_HOOK }}
        DISCORD_USERNAME: GEORGIE
      uses: tharitm/action-discord@master

